### ISSUE TITLE
Instructions in README to deploy the serverless demo app

### ISSUE THREAD

**Issue by lawrencepit** [aws-samples/amazon-chime-sdk-recording-demo#21]
The instructions in the README failed at this step:

```
node ./deploy.js -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting
```

Output:

```
yoda:~/environment/amazon-chime-sdk-js/demos/serverless (master) $ node ./deploy.js -r us-east-1 -b abc-amazon-chime-sdk-js-demo-serverless -s amazon-chime-sdk-js-demo-serverless -a me
eting
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/environment/amazon-chime-sdk-js/demos/serverless/deploy.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

The following does work:

```
npm install
npm run deploy -- -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting
```

**Comment by mrgrue** [comment]
I solved this by:

pushd ~/environment/amazon-chime-sdk-js
npm install fs-extra
popd

And then re-running the deploy.

**Comment by anuranduttaroy** [comment]
Updated README to add `npm install` command before deploying the [serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless).
